from __future__ import annotations

import os

from .base import ProviderModel, ProviderSpec


DEFAULT_CURSOR_MODEL = "auto"
DEFAULT_CURSOR_MODELS = ",".join(
    [
        "auto",
        "gpt-5.3-codex-low",
        "gpt-5.3-codex-low-fast",
        "gpt-5.3-codex",
        "gpt-5.3-codex-fast",
        "gpt-5.3-codex-high",
        "gpt-5.3-codex-high-fast",
        "gpt-5.3-codex-xhigh",
        "gpt-5.3-codex-xhigh-fast",
        "gpt-5.2",
        "gpt-5.2-codex-low",
        "gpt-5.2-codex-low-fast",
        "gpt-5.2-codex",
        "gpt-5.2-codex-fast",
        "gpt-5.2-codex-high",
        "gpt-5.2-codex-high-fast",
        "gpt-5.2-codex-xhigh",
        "gpt-5.2-codex-xhigh-fast",
        "gpt-5.1-codex-max-low",
        "gpt-5.1-codex-max-low-fast",
        "gpt-5.1-codex-max-medium",
        "gpt-5.1-codex-max-medium-fast",
        "gpt-5.1-codex-max-high",
        "gpt-5.1-codex-max-high-fast",
        "gpt-5.1-codex-max-xhigh",
        "gpt-5.1-codex-max-xhigh-fast",
        "grok-4.5-xhigh",
        "grok-4.5-fast-xhigh",
        "composer-2.5",
        "claude-opus-4-8-thinking-high",
        "claude-opus-4-8-thinking-high-fast",
        "gpt-5.5-high",
        "gpt-5.5-high-fast",
        "claude-fable-5-thinking-high",
        "claude-fable-5-thinking-xhigh",
        "claude-opus-4-7-thinking-high",
        "claude-opus-4-7-thinking-high-fast",
        "gpt-5.4-high",
        "gpt-5.4-high-fast",
        "grok-4.5-medium",
        "grok-4.5-fast-medium",
        "grok-4.5-high",
        "grok-4.5-fast-high",
        "composer-2.5-fast",
        "claude-opus-4-8-low",
        "claude-opus-4-8-low-fast",
        "claude-opus-4-8-medium",
        "claude-opus-4-8-medium-fast",
        "claude-opus-4-8-high",
        "claude-opus-4-8-high-fast",
        "claude-opus-4-8-xhigh",
        "claude-opus-4-8-xhigh-fast",
        "claude-opus-4-8-max",
        "claude-opus-4-8-max-fast",
        "claude-opus-4-8-thinking-low",
        "claude-opus-4-8-thinking-low-fast",
        "claude-opus-4-8-thinking-medium",
        "claude-opus-4-8-thinking-medium-fast",
        "claude-opus-4-8-thinking-xhigh",
        "claude-opus-4-8-thinking-xhigh-fast",
        "claude-opus-4-8-thinking-max",
        "claude-opus-4-8-thinking-max-fast",
        "gpt-5.5-none",
        "gpt-5.5-none-fast",
        "gpt-5.5-low",
        "gpt-5.5-low-fast",
        "gpt-5.5-medium",
        "gpt-5.5-medium-fast",
        "gpt-5.5-extra-high",
        "gpt-5.5-extra-high-fast",
        "claude-fable-5-low",
        "claude-fable-5-medium",
        "claude-fable-5-high",
        "claude-fable-5-xhigh",
        "claude-fable-5-max",
        "claude-fable-5-thinking-low",
        "claude-fable-5-thinking-medium",
        "claude-fable-5-thinking-max",
        "claude-sonnet-5-low",
        "claude-sonnet-5-medium",
        "claude-sonnet-5-high",
        "claude-sonnet-5-xhigh",
        "claude-sonnet-5-max",
        "claude-sonnet-5-thinking-low",
        "claude-sonnet-5-thinking-medium",
        "claude-sonnet-5-thinking-high",
        "claude-sonnet-5-thinking-xhigh",
        "claude-sonnet-5-thinking-max",
        "claude-4.6-sonnet-medium",
        "claude-4.6-sonnet-medium-thinking",
        "claude-opus-4-7-low",
        "claude-opus-4-7-low-fast",
        "claude-opus-4-7-medium",
        "claude-opus-4-7-medium-fast",
        "claude-opus-4-7-high",
        "claude-opus-4-7-high-fast",
        "claude-opus-4-7-xhigh",
        "claude-opus-4-7-xhigh-fast",
        "claude-opus-4-7-max",
        "claude-opus-4-7-max-fast",
        "claude-opus-4-7-thinking-low",
        "claude-opus-4-7-thinking-low-fast",
        "claude-opus-4-7-thinking-medium",
        "claude-opus-4-7-thinking-medium-fast",
        "claude-opus-4-7-thinking-xhigh",
        "claude-opus-4-7-thinking-xhigh-fast",
        "claude-opus-4-7-thinking-max",
        "claude-opus-4-7-thinking-max-fast",
        "gpt-5.4-low",
        "gpt-5.4-medium",
        "gpt-5.4-medium-fast",
        "gpt-5.4-xhigh",
        "gpt-5.4-xhigh-fast",
        "claude-4.6-opus-high",
        "claude-4.6-opus-max",
        "claude-4.6-opus-high-thinking",
        "claude-4.6-opus-max-thinking",
        "claude-4.5-opus-high",
        "claude-4.5-opus-high-thinking",
        "gpt-5.2-low",
        "gpt-5.2-low-fast",
        "gpt-5.2-fast",
        "gpt-5.2-high",
        "gpt-5.2-high-fast",
        "gpt-5.2-xhigh",
        "gpt-5.2-xhigh-fast",
        "gemini-3.1-pro",
        "gpt-5.4-mini-none",
        "gpt-5.4-mini-low",
        "gpt-5.4-mini-medium",
        "gpt-5.4-mini-high",
        "gpt-5.4-mini-xhigh",
        "gpt-5.4-nano-none",
        "gpt-5.4-nano-low",
        "gpt-5.4-nano-medium",
        "gpt-5.4-nano-high",
        "gpt-5.4-nano-xhigh",
        "claude-4.5-sonnet",
        "claude-4.5-sonnet-thinking",
        "gpt-5.1-low",
        "gpt-5.1",
        "gpt-5.1-high",
        "gemini-3-flash",
        "gemini-3.5-flash",
        "gpt-5.1-codex-mini-low",
        "gpt-5.1-codex-mini",
        "gpt-5.1-codex-mini-high",
        "claude-4-sonnet",
        "claude-4-sonnet-thinking",
        "gpt-5-mini",
        "kimi-k2.7-code",
        "glm-5.2-high",
        "glm-5.2-max",
    ]
)


class CursorAgentProviderFactory:
    backend_id = "cursor_agent"

    def from_env(self) -> ProviderSpec:
        return ProviderSpec(
            backend_id=self.backend_id,
            route_prefix="cursor",
            display_name=os.getenv("CURSOR_PROXY_DISPLAY_NAME", "Cursor"),
            default_model=os.getenv("CURSOR_DEFAULT_MODEL", DEFAULT_CURSOR_MODEL),
            models=self._models_from_env(),
            owned_by="cursor-agent-cli",
            catalog_description="Cursor model accessed through the local Cursor Agent CLI proxy.",
            comp_hash="cursor-agent-proxy-v1",
            runner_description="local Cursor Agent CLI",
        )

    def _models_from_env(self) -> tuple[ProviderModel, ...]:
        raw_names = os.getenv("CURSOR_MODELS", DEFAULT_CURSOR_MODELS)
        names = [name.strip() for name in raw_names.split(",") if name.strip()]
        if not names:
            names = [DEFAULT_CURSOR_MODEL]
        return tuple(
            ProviderModel(
                slug=name,
                display_name=self._display_name(name),
                aliases=self._aliases_for(name),
            )
            for name in names
        )

    @staticmethod
    def _display_name(name: str) -> str:
        if name == "auto":
            return "Auto"
        return name.replace("-", " ").replace("_", " ").title()

    @staticmethod
    def _aliases_for(name: str) -> tuple[str, ...]:
        aliases: dict[str, tuple[str, ...]] = {
            "auto": ("cursor-auto",),
            "gpt-5.3-codex": ("cursor-codex",),
            "gpt-5.3-codex-high": ("cursor-codex-high",),
            "gpt-5.3-codex-xhigh": ("cursor-codex-xhigh",),
            "composer-2.5": ("composer", "cursor-composer"),
            "grok-4.5-xhigh": ("cursor-grok", "grok-4.5"),
            "claude-opus-4-8-thinking-high": ("cursor-opus", "claude-opus-4-8", "opus"),
            "claude-sonnet-5-thinking-high": ("cursor-sonnet", "claude-sonnet-5", "sonnet"),
            "claude-fable-5-thinking-high": ("cursor-fable", "claude-fable-5", "fable"),
            "gpt-5.5-high": ("cursor-gpt", "gpt-5.5", "cursor-gpt-5.5"),
            "gpt-5.4-high": ("gpt-5.4", "cursor-gpt-5.4"),
            "gpt-5.4-mini-medium": ("gpt-5.4-mini", "cursor-gpt-mini"),
            "gemini-3.1-pro": ("cursor-gemini", "gemini-3-1-pro"),
            "gemini-3.5-flash": ("cursor-gemini-flash",),
            "kimi-k2.7-code": ("cursor-kimi",),
            "glm-5.2-high": ("cursor-glm",),
        }
        return aliases.get(name, ())
